baseURL = 'https://robbrooks.run/'
languageCode = 'en-us'
title = 'Rob Brooks Run'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2","hugo-shortcode-gallery"]

timeout = 600000 # This is requiered for larger galleries to be build
defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = "Rob Brooks"
favicon = ""
site_logo = ""
description = ""
# choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
featured_image = "../images/rob.jpeg"
recent_posts_number = 10
show_reading_time = "true"
loadJQuery = "true"
galleryLoadJQuery = "true"
galleryRowHeight    = 200
galleryMargins      = 10
galleryResizeOptions= "800x800 q88 Lanczos"
galleryThumbnailHoverEffect = "enlarge"

[params.ananke.social.share]
networks = [
  "email",
  "facebook",
  "bluesky",
  "linkedin"
]

[params.ananke.social.follow]
networks = [
  "facebook",
  "youtube"
]

[params.ananke.social.youtube]
username = "Billybrewster334"

[params.ananke.social.facebook]
username = "rob.brooks.10297"

[imaging.exif]
    includeFields = ".*"

[menu]
[[menu.main]]
  identifier = 'posts'
  name = 'running'
  pre = "<i class='fa fa-heart'></i>"
  url = '/running/'
  weight = -110
[[menu.main]]
  name = 'video'
  post = "<span class='alert'>New!</span>"
  pre = "<i class='fa fa-road'></i>"
  url = '/video/'
  weight = -100
[[menu.main]]
  identifier = 'about'
  name = 'about'
  pre = "<i class='fa fa-heart'></i>"
  url = '/about/'
  weight = -110
[[menu.main]]
  identifier = 'itera'
  name = 'itera'
  pre = "<i class='fa fa-heart'></i>"
  url = '/itera/'
  weight = -110
[[menu.main]]
  identifier = 'fastpacking'
  name = 'fastpacking'
  pre = "<i class='fa fa-heart'></i>"
  url = '/fastpacking/'
  weight = -110
[[menu.main]]
  identifier = 'arctic'
  name = 'arctic'
  pre = "<i class='fa fa-heart'></i>"
  url = '/arctic/'
  weight = -110
